# Generated by Django 5.0 on 2024-01-21 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0005_remove_libro_autor_id_libro_autor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='apellido',
            new_name='apellidos',
        ),
    ]
