# Generated by Django 5.0 on 2024-01-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0006_rename_apellido_autor_apellidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='descripcion',
            field=models.TextField(blank=True, max_length=200, verbose_name='Descripcion'),
        ),
    ]
